# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MosaicCreate_export.py
# Created on: 2014-08-29 10:42:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: MosaicCreate_export <OUTPUT_FOLDER> <MosaicName> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
OUTPUT_FOLDER = arcpy.GetParameterAsText(0)
if OUTPUT_FOLDER == '#' or not OUTPUT_FOLDER:
    OUTPUT_FOLDER = "C:\\Users\\thare\\Documents\\GIT\\ArcGIS_Plugins\\CTX_CreateMosaic_fromASU" # provide a default value if unspecified

MosaicName = arcpy.GetParameterAsText(1)
if MosaicName == '#' or not MosaicName:
    MosaicName = "CTXmosaic" # provide a default value if unspecified

# Local variables:
CTX_Mosaic_Rasters = OUTPUT_FOLDER
CTX_Mosaic_NoDATA = CTX_Mosaic_Rasters
CTX_Mosaic_Footprints1 = CTX_Mosaic_NoDATA
CTX_Mosaic_Footprints2 = CTX_Mosaic_Footprints1
CTX_Final = CTX_Mosaic_Footprints2
CTXmosaic_GBD_gdb = OUTPUT_FOLDER
CTX_Mosaic_Init = CTXmosaic_GBD_gdb
CompleteDownload = "true"
ExpressionTF = "CompleteDown = \"false\""

# Process: Create File GDB
arcpy.CreateFileGDB_management(OUTPUT_FOLDER, MosaicName, "CURRENT")

# Process: Create Mosaic Dataset
arcpy.CreateMosaicDataset_management(CTXmosaic_GBD_gdb, MosaicName, "PROJCS['Mars_Equi180',GEOGCS['GCS_Mars_2000_Sphere',DATUM['D_Mars_2000_Sphere',SPHEROID['Mars_2000_Sphere_IAU_IAG',3396190.0,0.0]],PRIMEM['Reference_Meridian',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Equidistant_Cylindrical'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',180.0],UNIT['Meter',1.0]];-10669600 -16102700 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "1", "8_BIT_UNSIGNED", "NONE", "")

# Process: Add Rasters To Mosaic Dataset
arcpy.AddRastersToMosaicDataset_management(CTX_Mosaic_Init, "Raster Dataset", "C:\\Users\\thare\\Documents\\GIT\\ArcGIS_Plugins\\CTX_CreateMosaic_fromASU", "UPDATE_CELL_SIZES", "UPDATE_BOUNDARY", "NO_OVERVIEWS", "", "0", "1500", "", "*.JP2", "NO_SUBFOLDERS", "EXCLUDE_DUPLICATES", "NO_PYRAMIDS", "CALCULATE_STATISTICS", "NO_THUMBNAILS", "", "NO_FORCE_SPATIAL_REFERENCE")

# Process: Define Mosaic Dataset NoData
arcpy.DefineMosaicDatasetNoData_management(CTX_Mosaic_Rasters, "1", "BAND_1 0", "", "", "NO_COMPOSITE_NODATA")

# Process: BuildFootprints_1
arcpy.BuildFootprints_management(CTX_Mosaic_NoDATA, "", "RADIOMETRY", "1", "255", "10", "500", "NO_MAINTAIN_EDGES", "SKIP_DERIVED_IMAGES", "NO_BOUNDARY", "2000", "100", "NONE", "", "20", "0.05")

# Process: BuildFootprints_2
arcpy.BuildFootprints_management(CTX_Mosaic_Footprints1, "", "NONE", "1", "254", "10", "5000", "NO_MAINTAIN_EDGES", "SKIP_DERIVED_IMAGES", "UPDATE_BOUNDARY", "2000", "100", "NONE", "", "20", "0.05")

# Process: Set Mosaic Dataset Properties
arcpy.SetMosaicDatasetProperties_management(CTX_Mosaic_Footprints2, "4100", "15000", "None;LZ77;JPEG;LERC", "None", "75", "0", "BILINEAR", "CLIP", "FOOTPRINTS_MAY_CONTAIN_NODATA", "CLIP", "NOT_APPLY", "", "NONE", "Center;NorthWest;LockRaster;ByAttribute;Nadir;Viewpoint;Seamline;None", "Seamline", "", "", "ASCENDING", "BLEND", "10", "600", "300", "1000", "0.8", "", "FULL", "", "DISABLED", "", "", "", "", "20", "1000", "GENERIC", "1")

# Process: Calculate Value
arcpy.CalculateValue_management(ExpressionTF, "", "Boolean")

